kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/drone
    - refs/pull/**
    - refs/tags/**

steps:
  - name: build
    image: registry.digitalocean.com/stewcasa/elm-builder:18
    commands:
      - 
      - mkdir /opt/codebase-ui
      - export API_TOKEN=notsecret
      - export API_URL=http://localhost:26116
      - . /root/.nvm/nvm.sh && npm run makeElmEnv
      - elm make --output=/opt/codebase-ui/index.html src/Main.elm
      - tar -c -z -C /opt -f casebase-ui-$DRONE_BUILD_NUMBER.tar.gz codebase-ui 
